### ISSUE TITLE
Re-construct Logo

### ISSUE THREAD

**Issue by ZainSohail** [Abolitionist-Project/QuantiModo-Sync-Android#44]
@jentrifule 

Mike wants you to Re-construct our QuantiModo Sync Logo.

It should be a new High Resoloution version of our QuandiModo Sync Logo.

Please put all files here: https://drive.google.com/folderview?id=0B5728AmQzoPQTWpuSTdVR29aVWs&usp=sharing

and in the wiki.

**Comment by mikepsinn** [comment]
@Quipeace do you know if we have an ai file of that somewhere or should jentri make a new one?

**Comment by quintstoffers** [comment]
I don't have sources. I constructed the current logo from what I had within
reach.

Either way, the logo's colours are out of date, and we'll want to decide on
a final QM logo for apps (should be similar to the large logo on the site)

**Comment by jentrifule** [comment]
What should be similar to what I will make? Can I see it?

**Comment by mikepsinn** [comment]
@jentrifule please call me at the beginning of your shift (and every shift as described here: http://abolitionistproject.info/work-guidelines/).  Thanks!

**Comment by mikepsinn** [comment]
https://www.dropbox.com/s/18h1hwxbh6zx5n6/quantimodo-sync-android-logo-icon-512.png

**Comment by jentrifule** [comment]
@mikepsinn Here are some versions I made. Let me know your thoughts. Thank you.

![quantimodo sync logo 512x512 v3](https://f.cloud.github.com/assets/4625974/2345503/14ed19f6-a536-11e3-8bbc-338fa88da1e7.png)
![quantimodo sync logo 512x512 v1](https://f.cloud.github.com/assets/4625974/2345504/14f63856-a536-11e3-8a0b-208f1617c748.png)
![quantimodo sync logo 512x512 v2](https://f.cloud.github.com/assets/4625974/2345505/150355d6-a536-11e3-87c1-db92bc0a5816.png)

**Comment by mikepsinn** [comment]
@jentrifule 

Please make another and use this as a basis: https://drive.google.com/file/d/0B5bXsrxQCOy8elZmV3V3N2pkYW8/edit?usp=sharing

We just need to take the one that's in there, but complete the circle (now there's black space because i just mirrored the rainbow and it has a black border. Then we need to put the arrows going around it and have an arrow going into the center.

**Comment by mikepsinn** [comment]
Please put all QM-Sync files in this folder:
https://drive.google.com/folderview?id=0B5728AmQzoPQTFIwUEtienAwTjA&usp=sharing
and in the Wiki. Thanks!

**Comment by mikepsinn** [comment]
also put the arrow going into the circle on your other versions so it looks like a Q

**Comment by quintstoffers** [comment]
I think the first one looks awesome, but there's nothing that says
"QuantiModo". You can have one of the arrows wrap around the circle, then
come through the centre and form a "Q". A quick Paint mockup:
http://i.imgur.com/86Czdu1.png

**Comment by quintstoffers** [comment]
Also, for Android icons have a look at the iconograpy guidelines (under
"Launcher"):
http://developer.android.com/design/style/iconography.html

Specifically:
"Use a distinct silhouette. Three-dimensional, front view, with a slight
perspective as if viewed from above, so that users perceive some depth."
http://developer.android.com/design/media/iconography_launcher_style.png

**Comment by mikepsinn** [comment]
@jentrifule  This is probably the top priority

We also need a slider and featured image for this:
https://quantimo.do/portfolio/quantimodo-sync/

We also want to list all the apps that can be synced with QM sync. 

It would be cool if you included their logos in the slider.

**Comment by jentrifule** [comment]
So I will be having this as my basis https://drive.google.com/file/d/0B5bXsrxQCOy8elZmV3V3N2pkYW8/edit?usp=sharing and consider what @Quipeace said.

**Comment by mikepsinn** [comment]
Right.  We want to complete the circle so we don't have that black horizontal through the middle. 

And we want an arrow going into the circle so it looks like a Q.

**Comment by jentrifule** [comment]
Hi @mikepsinn Please see the image here and let me know your thoughts.
Thank you.
![logo v3](https://f.cloud.github.com/assets/4625974/2370717/986b8788-a80e-11e3-9e51-71d0c95fcef2.png)

**Comment by jentrifule** [comment]
V3 with arrow.
![quantimodo sync logo 512x512 v3](https://f.cloud.github.com/assets/4625974/2370894/07513114-a816-11e3-858e-edc3732ca666.png)

**Comment by jentrifule** [comment]
https://quantimo.do/wp-admin/admin.php?page=layerslider&action=edit&id=20

**Comment by quintstoffers** [comment]
The white of the arrow in the lower right won't be visible on light
backgrounds, so you might want to add some sort of outline.

You'll also want that top down look from the iconography guidelines. That'd
probably help with the arrow as well. Perhaps have all those different
segments lay on top of each other with a slight edge at the top for the 3d
effect?

https://quantimo.do/wp-admin/admin.php?page=layerslider&action=edit&id=20

## 

Reply to this email directly or view it on
GitHubhttps://github.com/mikepsinn/QuantiModo-Sync-Android/issues/44#issuecomment-37164430
.

**Comment by quintstoffers** [comment]
You can take their circular icon example, paste your logo on top of it and
tweak the shadow colour at the top, that'd be an improvement already.

**Comment by jentrifule** [comment]
Thanks @Quipeace, so far, here's what I have done. Do you think this would work?
![ss](https://f.cloud.github.com/assets/4625974/2372239/89d52d04-a837-11e3-8e21-b790f33e0e92.png)

**Comment by quintstoffers** [comment]
The blob around it? The original was better.

**Comment by jentrifule** [comment]
![logo v3 3](https://f.cloud.github.com/assets/4625974/2372296/7cfc28f2-a838-11e3-852a-e5fa85e56bb2.png)
Would this work?

**Comment by jentrifule** [comment]
I will just make some outlines later. I've just added a background color here to see the logo fully. Be back later.
![logo v3 4](https://f.cloud.github.com/assets/4625974/2372316/e1955ebe-a838-11e3-954d-564198f36d88.png)

**Comment by jentrifule** [comment]
![logo v3](https://f.cloud.github.com/assets/4625974/2380945/fd230b0e-a8b5-11e3-9b56-6d1540e5ca6c.png)

**Comment by jentrifule** [comment]
![quantimodo sync logo iconography](https://f.cloud.github.com/assets/4625974/2381733/36daccdc-a8cb-11e3-8e86-a6ae8de0bf3f.png)

**Comment by mikepsinn** [comment]
https://www.evernote.com/shard/s1/sh/6051283a-f25c-4342-9ef7-42f04a49f00c/aaa29d3b83a38cc635f7b3d9c98514cb

I, personally, would like one just like this.

**Comment by mikepsinn** [comment]
I mean this: https://www.evernote.com/shard/s1/sh/ea4f42a9-3ec7-4286-87f8-eb5410ac03f2/433da514108e92f52a5e5a591c280371

but with the colors.  I would like the border of arrow to be the same width as the black circles.

**Comment by mikepsinn** [comment]
It seems to me that we already had this pretty much done a couple days ago. 

Please use this as a basis: 
https://drive.google.com/file/d/0B5bXsrxQCOy8elZmV3V3N2pkYW8/edit?usp=sharing

We just need to take the one that's in there, but complete the circle (now there's black space because i just mirrored the rainbow and it has a black border). 

Then we need to put the symmetrical DataSync arrows going around it.

We need to have an arrow going into the center. I would like the black border of the arrow going into the center to be the same width as the black circles like this: https://www.evernote.com/shard/s1/sh/ea4f42a9-3ec7-4286-87f8-eb5410ac03f2/433da514108e92f52a5e5a591c280371

The shadowing that you've done is fine. 

Thanks!

**Comment by jentrifule** [comment]
Yeah @mikepsinn I've done these:
"It seems to me that we already had this pretty much done a couple days ago.

Please use this as a basis: 
https://drive.google.com/file/d/0B5bXsrxQCOy8elZmV3V3N2pkYW8/edit?usp=sharing

We just need to take the one that's in there, but complete the circle (now there's black space because i just mirrored the rainbow and it has a black border).

We need to have an arrow going into the center."
And it looked something like this.
https://f.cloud.github.com/assets/4625974/2370717/986b8788-a80e-11e3-9e51-71d0c95fcef2.png

I think I just have to do the remaining stuff.

**Comment by mikepsinn** [comment]
excellent. Thanks!

**Comment by jentrifule** [comment]
![logo v5](https://f.cloud.github.com/assets/4625974/2381972/e03a96da-a8d1-11e3-8436-7dd990811da9.png)

**Comment by quintstoffers** [comment]
That looks better, but it's as if you're looking from the bottom instead of
the top because you've only got that shadow at the bottom, and not a
surface at the top.

I also noticed aren't completely round, the gap between the inner circle
and the blue arrow is bigger than the one between the orange arrow and the
middle, and the gap isn't a constant width either.

**Comment by mikepsinn** [comment]
@jentrifule please put all the files for all your versions here: https://drive.google.com/folderview?id=0B5728AmQzoPQTWpuSTdVR29aVWs&usp=sharing

**Comment by mikepsinn** [comment]
@jentrifule add whatever logos you have now to the portfolio projects, the chrome extension, and the android apps, ASAP.  

Then later you can fix the symmetry, shadowing, and make the black border of the arrow going into the center to be the same width as the black circles like this: https://www.evernote.com/shard/s1/sh/ea4f42a9-3ec7-4286-87f8-eb5410ac03f2/433da514108e92f52a5e5a591c280371

After those are fixed, update the play store, portfolios, and extension again. 

Thanks!

**Comment by jentrifule** [comment]
https://github.com/mikepsinn/QuantiModo-Sync-Android/wiki/Google-Play-Store
https://drive.google.com/folderview?id=0B5728AmQzoPQTWpuSTdVR29aVWs&usp=sharing

**Comment by mikepsinn** [comment]
@jentrifule are you exporting your work as xml and committing those top the repository every day?

**Comment by mikepsinn** [comment]
@jentrifule please copy all different versions of the logos from the different ai files into a single ai file.  Then delete all the redundant ai files.  

Then put all versions of the logos here and on thumb.it at 512 by 512 resolution

thanks!

**Comment by jentrifule** [comment]
For QuantiModo-Sync App.
![ss3](https://cloud.githubusercontent.com/assets/4625974/2535071/09123b9a-b588-11e3-8b96-791ad2c2c9a7.png)

**Comment by jentrifule** [comment]
Quantimodo-Sync PNG link:
https://docs.google.com/file/d/0B-t22a_LObpzSlFrdEkzaVdndUk/edit
All vector logos in one AI file:
https://docs.google.com/file/d/0B-t22a_LObpzMy0xTHlmbVgybU0/edit
I am updating the graphics in every portfolio on the website.

**Comment by mikepsinn** [comment]
Thanks! Were we able to get any more versions of qm sync on thumb.it?

**Comment by jentrifule** [comment]
The first one's ring has the same color as the circles inside.
![ss4](https://cloud.githubusercontent.com/assets/4625974/2538881/8b013d06-b5c2-11e3-8fa6-7e04684200eb.png)

**Comment by mikepsinn** [comment]
![](https://cloud.githubusercontent.com/assets/4625974/2538881/8b013d06-b5c2-11e3-8fa6-7e04684200eb.png)

Can you make one like the bottom one but with this in the center?
![qm-logo-icon-black-circles-512-mike](https://cloud.githubusercontent.com/assets/2808553/2553294/ac8ec18c-b6a3-11e3-8cc5-31f4f6f442f6.jpg)

Also, what's the link to the AI file with everything in it?  I can't find it.

**Comment by quintstoffers** [comment]
The bottom one would probably look better if you make the outermost black
circle transparent. That looks great on Android home screens and makes it
pop out.

**Comment by mikepsinn** [comment]
Like 50% transparent or completely transparent?

**Comment by quintstoffers** [comment]
Completely, take DataSync's icon for example.

**Comment by mikepsinn** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/2808553/2553763/194c46d2-b6a9-11e3-81a6-58adc8c9cd7b.png)

**Comment by mikepsinn** [comment]
Do you have a PSD or 512px version of that?

**Comment by quintstoffers** [comment]
I do, somewhere. The DataSync icon was just as an example though.

**Comment by mikepsinn** [comment]
https://github.com/Abolitionist-Project/QM-Sync-Android/commit/2821993bbd57a7b6520332713abeeb3d02bc2102
